name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Luver
        uses: ./
        with:
          lua_versions: 5.1.5 5.4.3
          luajit_versions: 5.1.5:2.1.0-beta3
          luarocks_versions: 5.1.5:3.7.0 5.4.3:3.8.0
      - name: Validate
        shell: bash
        run: |
          set -euo pipefail

          luver use 5.1.5

          test "$(luver current lua)" = "5.1.5"
          test "$(luver current luajit)" = "2.1.0-beta3"
          test "$(luver current luarocks)" = "3.7.0"

          luver use 5.4.3

          test "$(luver current lua)" = "5.4.3"
          test "$(luver current luarocks)" = "3.8.0"
